#frontend BuildKit
#syntax=docker/dockerfile:1.4

FROM node:18-alpine AS builder
#autor
LABEL org.opencontainers.image.authors="Krzysztof Ksiezki"

# git + ssh
RUN apk add --no-cache git openssh-client ca-certificates

#katalog roboczy
WORKDIR /app

#połączenie ssh,pobranie kodu z repo z GitHub przez ssh
RUN --mount=type=ssh \
    --mount=type=cache,id=npm,target=/root/.npm \
    mkdir -p /root/.ssh && \
    ssh-keyscan github.com >> /root/.ssh/known_hosts && \
    git clone git@github.com:NAZWA_KONTA/NAZWA_REPO . && \
    npm ci --only=production

FROM node:18-alpine AS runtime
LABEL org.opencontainers.image.authors="Krzysztof Ksiezki"
#usuwanie npm
RUN rm -rf /usr/local/lib/node_modules/npm

WORKDIR /app

#kopiowanie z buildera
COPY --from=builder /app .

ENV PORT=3000
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://localhost:3000 || exit 1

CMD ["node","server.js"]
